[project]
name = "irc_message"
authors = ["TyOverby <ty@pre-alpha.com>"]
version = "0.0.4"

repository = "https://github.com/TyOverby/irc-message"
license = "MIT"
description = "A small library for parsing irc messages."

[lib]
name = "irc_message"
path = "./src/lib.rs"
